// ---------------- IMPORTANT - GENERATED FILE ----------------
//
// This file is generated by git hooks.
//
// Execute the following command in the seedtool directory to ensure it
// gets updated in your tree:
//
//     ./enable-gitrevision-hooks.sh
//
// See the README.md in this directory for more information ...
//

#ifndef GITREVISION_H
#define GITREVISION_H

#define GIT_BRANCH "------"
#define GIT_SHORT_HASH "-------"
#define GIT_LATEST_TAG "------"
#define GIT_REV_COUNT "---"

#endif // GITREVISION_H
