// ---------------- IMPORTANT - GENERATED FILE ----------------
//
// This file is generated by git hooks.
//
// Execute the following command in the seedtool directory to ensure it
// gets updated in your tree:
//
//     ./enable-gitrevision-hooks.sh
//
// See the README.md in this directory for more information ...
//

#ifndef GITREVISION_H
#define GITREVISION_H

#define GIT_BRANCH "gxepd2-sw-spi"
#define GIT_SHORT_HASH "81a3aff"
#define GIT_LATEST_TAG "v0.4.5"
#define GIT_REVS_SINCE 8
#define GIT_DESCRIBE "v0.4.5-8-g81a3aff"

#endif // GITREVISION_H
